baseURL = 'https://blog.rbtreefence.xyz/'
languageCode = 'zh-cn'
DefaultContentLanguage = 'zh-cn'
title = 'RBTree On the Fence'
enableInlineShortcodes = true
hasCJKLanguage = true


[menu]
[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"


[module]
[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# [services]
#   [services.disqus]
#     shortname = 'YOUR_DISQUS_SHORTNAME'     # use disqus comments

[params]
author = 'RBTree'
mainSections = ['posts']
defaultTheme = 'dark'
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = false
ShowBreadCrumbs = true

[params.homeInfoParams]
Content = """
- 👋 你好，欢迎来到我的Blog。

- RBTree是红黑树，因为每次看到红黑树我就头疼，遗忘速度仅次于KMP，所以不如拿最头疼的概念当在线身份好了。
"""

# [[params.socialIcons]]
# name = 'github'
# url = 'https://github.com/jiyangzh'

[[params.socialIcons]]
name = 'mastodon'
url = 'https://mastodon.social/@rbtree27'

[[params.socialIcons]]
name = 'rss'
url = '/index.xml'

[outputs]
home = ['HTML', 'RSS', 'JSON']
