baseURL = 'https://blog.rbtreefence.xyz/'
languageCode = 'zh-cn'
DefaultContentLanguage = 'zh-cn'
title = 'RBTree On the Fence'
enableInlineShortcodes = true
hasCJKLanguage = true
theme = 'PaperMod'

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[taxonomies]
category = "categories"
tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
defaultTheme = 'light'
author = 'RBTree'
mastodon = 'https://mastodon.social/@rbtree27'
avatar = 'https://files.mastodon.social/accounts/avatars/115/707/959/569/272/437/original/a8b470bb203793c9.png'
name = 'RBTree'
bio = '好奇心和自我探索'
siteStart = '2026-02-21T00:00:00Z'
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
comments = true

[params.homeInfoParams]
Content = '好奇心和自我探索'

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@rbtree27"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[params.twikoo]
envId = "https://twikoo-comment-rbtree.netlify.app/.netlify/functions/twikoo"
